spring:
  application:
    name: ms-commerce

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: validate
    open-in-view: false

server:
  port: ${PORT}

eureka:
  instance:
    hostname: ${EUREKA_SERVER_DOMAIN:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_DOMAIN}/eureka/
    fetch-registry: true
    register-with-eureka: true


      #RAILWAY_PUBLIC_DOMAIN #http://localhost:8761/eureka
