spring:
  application:
    name: ms-commerce

  datasource:
    url: jdbc:mysql://root:RoMBBzsMYCGVecgwguuzMAfkjAIGGJwW@roundhouse.proxy.rlwy.net:53234/railway
    username: root
    password: RoMBBzsMYCGVecgwguuzMAfkjAIGGJwW
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: validate
    open-in-view: false

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://${RAILWAY_PUBLIC_DOMAIN}/eureka/



      #RAILWAY_PUBLIC_DOMAIN #http://localhost:8761/eureka
